import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as pdfjsLib from 'pdfjs-dist';

// Configure PDF.js worker
if (typeof window !== 'undefined') {
    pdfjsLib.GlobalWorkerOptions.workerSrc = '/pdf.worker.min.mjs';
}

/**
 * Convert PDF to Excel Workbook (XLSX)
 * Extracts text and attempts to reconstruct tables based on layout
 */
export async function pdfToExcel(file: File): Promise<Uint8Array> {
    const arrayBuffer = await file.arrayBuffer();
    const loadingTask = pdfjsLib.getDocument({ data: arrayBuffer });
    const pdfDoc = await loadingTask.promise;

    const workbook = XLSX.utils.book_new();

    // Process each page
    for (let pageNum = 1; pageNum <= pdfDoc.numPages; pageNum++) {
        const page = await pdfDoc.getPage(pageNum);
        const textContent = await page.getTextContent();

        // Group items by Y coordinate (rows)
        // Fuzzy matching for Y coordinates to handle slight misalignments
        const rows: Record<string, { x: number, str: string }[]> = {};

        textContent.items.forEach((item: any) => {
            const y = Math.round(item.transform[5]); // Round to nearest integer for grouping
            if (!rows[y]) rows[y] = [];
            rows[y].push({ x: item.transform[4], str: item.str });
        });

        // Sort items in each row by X coordinate
        Object.keys(rows).forEach(y => {
            rows[y].sort((a, b) => a.x - b.x);
        });

        // Convert to 2D array (Rows sorted by Y descending - PDF coords start from bottom)
        const sortedY = Object.keys(rows).sort((a, b) => parseInt(b) - parseInt(a));
        const sheetData: string[][] = [];

        sortedY.forEach(y => {
            const rowData = rows[y].map(item => item.str);
            sheetData.push(rowData);
        });

        const sheetName = `Page ${pageNum}`;
        const worksheet = XLSX.utils.aoa_to_sheet(sheetData);
        XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
    }

    // Write to buffer
    const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
    return new Uint8Array(excelBuffer);
}

/**
 * Convert Excel to PDF
 * Renders the first sheet of the Excel file into a PDF table
 */
export async function excelToPdf(file: File): Promise<Uint8Array> {
    const arrayBuffer = await file.arrayBuffer();
    const workbook = XLSX.read(arrayBuffer);

    // Use first sheet
    const firstSheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[firstSheetName];

    // Convert to JSON data for autoTable
    const jsonData: any[][] = XLSX.utils.sheet_to_json(worksheet, { header: 1 });

    const doc = new jsPDF();

    // Add Branding
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text('Generated by PDFToolskit', 14, 10);

    doc.setFontSize(18);
    doc.setTextColor(0);
    doc.text(file.name.replace(/\.[^/.]+$/, ""), 14, 20);

    // Generate Table
    if (jsonData.length > 0) {
        autoTable(doc, {
            startY: 25,
            head: [jsonData[0]], // First row as header
            body: jsonData.slice(1),
            theme: 'grid',
            styles: { fontSize: 8 },
            headStyles: { fillColor: [66, 133, 244] }, // Blue header
        });
    } else {
        doc.text("No data found in Excel sheet.", 14, 30);
    }

    return new Uint8Array(doc.output('arraybuffer'));
}
