import jsPDF from 'jspdf';
import mammoth from 'mammoth';

/**
 * Convert Word (DOCX) to PDF
 * Uses mammoth.js for high-fidelity HTML reconstruction and jsPDF for rendering.
 * Note: Client-side only. Significantly more robust than raw XML parsing.
 */
export async function wordToPdf(file: File): Promise<Uint8Array> {
    const arrayBuffer = await file.arrayBuffer();

    // 1. Convert DOCX to HTML using mammoth
    // This preserves tables, images, and styling (bold, italic, etc.)
    const result = await mammoth.convertToHtml({ arrayBuffer });
    const html = result.value;

    // 2. Wrap HTML in a container with basic styling for PDF rendering
    const container = document.createElement('div');
    container.style.width = '750px'; // Approx A4 width in pixels at standard DPI
    container.style.padding = '40px';
    container.style.backgroundColor = 'white';
    container.style.color = 'black';
    container.style.fontFamily = 'Arial, sans-serif';
    container.style.lineHeight = '1.6';
    container.innerHTML = `
        <style>
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            img { max-width: 100%; height: auto; display: block; margin: 10px 0; }
            p { margin-bottom: 15px; }
            h1, h2, h3 { margin-top: 25px; margin-bottom: 15px; }
        </style>
        ${html}
    `;

    // 3. Render HTML to PDF using jsPDF's .html() method
    // We append to document temporarily for rendering (jspdf.html requirement)
    document.body.appendChild(container);

    try {
        const doc = new jsPDF({
            orientation: 'p',
            unit: 'px',
            format: 'a4',
            hotfixes: ['px_scaling']
        });

        await new Promise<void>((resolve, reject) => {
            doc.html(container, {
                callback: (pdf) => {
                    resolve();
                },
                x: 0,
                y: 0,
                autoPaging: 'text',
                width: 790, // target width in pixels
                windowWidth: 790, // window width in pixels
                margin: [40, 40, 40, 40]
            });
        });

        // Add Branding / Footer to all pages
        const totalPages = doc.getNumberOfPages();
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();

        for (let i = 1; i <= totalPages; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Page ${i} of ${totalPages} | Generated by PDFToolskit`, pageWidth / 2, pageHeight - 10, { align: 'center' });
        }

        return new Uint8Array(doc.output('arraybuffer'));
    } finally {
        // Cleanup the temporary container
        document.body.removeChild(container);
    }
}
