import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ExcelToPdfOptions {
    orientation: 'p' | 'l';
    sheets: 'all' | string[];
    preserveStyles: boolean;
}

export async function excelToPdf(
    file: File,
    options: ExcelToPdfOptions
): Promise<Uint8Array> {
    const arrayBuffer = await file.arrayBuffer();
    const workbook = XLSX.read(arrayBuffer);

    const doc = new jsPDF({
        orientation: options.orientation,
        unit: 'mm',
        format: 'a4'
    });

    const sheetNames = options.sheets === 'all'
        ? workbook.SheetNames
        : workbook.SheetNames.filter(name => options.sheets.includes(name));

    sheetNames.forEach((sheetName, index) => {
        if (index > 0) doc.addPage();

        const worksheet = workbook.Sheets[sheetName];
        const jsonData: any[][] = XLSX.utils.sheet_to_json(worksheet, { header: 1 });

        if (jsonData.length === 0) {
            doc.text(`Sheet "${sheetName}" is empty.`, 14, 20);
            return;
        }

        // Add Sheet Header
        doc.setFontSize(14);
        doc.setTextColor(40);
        doc.text(sheetName, 14, 15);

        // Map styles if requested
        let bodyStyles: any = {};
        if (options.preserveStyles) {
            // Simplified style mapping: detect if a row is likely a header or has colors
            // Real Excel style mapping is complex with SheetJS/jsPDF-AutoTable
            // We'll focus on header detection and row banding
        }

        autoTable(doc, {
            startY: 20,
            head: [jsonData[0]],
            body: jsonData.slice(1),
            theme: 'grid',
            styles: {
                fontSize: 8,
                cellPadding: 2,
                overflow: 'linebreak'
            },
            headStyles: {
                fillColor: [34, 197, 94], // Green theme for Excel
                textColor: [255, 255, 255]
            },
            alternateRowStyles: {
                fillColor: [240, 253, 244]
            },
            margin: { top: 20, bottom: 20 },
            didDrawPage: (data) => {
                // Add footer
                doc.setFontSize(8);
                doc.setTextColor(150);
                const pageCount = (doc as any).internal.getNumberOfPages();
                doc.text(
                    `Page ${data.pageNumber} of ${pageCount} | Generated by PDFToolskit`,
                    14,
                    doc.internal.pageSize.height - 10
                );
            }
        });
    });

    return new Uint8Array(doc.output('arraybuffer'));
}

export async function getWorkbookInfo(file: File) {
    const arrayBuffer = await file.arrayBuffer();
    const workbook = XLSX.read(arrayBuffer);
    return {
        sheetNames: workbook.SheetNames,
        totalSheets: workbook.SheetNames.length
    };
}
