/* eslint-disable */
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import JSZip from 'jszip';
import fontkit from '@pdf-lib/fontkit';

export interface OfficeToPdfOptions {
    addBranding?: boolean;
    onProgress?: (progress: number) => void;
}

export async function officeToPdf(file: File, options: OfficeToPdfOptions = {}): Promise<Uint8Array> {
    const arrayBuffer = await file.arrayBuffer();

    // --- PHASE 35.1: Uncompromising Structural Generation (WASM) ---
    // Instead of processing the XML natively in JS, we offload the heavy lifting to the C++ Core Rendering Engine 
    // compiled to WebAssembly. This preserves headers, footers, and complex nested styles flawlessly.
    const wasmPdfBytes = await new Promise<Uint8Array | null>((resolve) => {
        const worker = new Worker(new URL('../../../engines/apex-core.worker.ts', import.meta.url), { type: 'module' });

        worker.postMessage({ type: 'INIT_ENGINE', payload: { engineType: 'LIBRE_OFFICE' }, id: '1' });
        worker.onmessage = (e) => {
            if (e.data.type === 'SUCCESS' && e.data.id === '1') {
                // Engine initialized, dispatch the raw file into Emscripten Virtual File System
                worker.postMessage({
                    type: 'EXECUTE_WASM_LAYOUT_PASS',
                    payload: { fileBuffer: new Uint8Array(arrayBuffer), fileName: file.name },
                    id: '2'
                });
            } else if (e.data.type === 'SUCCESS' && e.data.id === '2') {
                worker.terminate();
                resolve(e.data.payload);
            } else if (e.data.type === 'ERROR') {
                worker.terminate();
                console.warn("WASM Engine Error, falling back to Native Parser", e.data.error);
                resolve(null);
            }
        };
    });

    if (wasmPdfBytes && wasmPdfBytes.length > 100) {
        console.log(`🚀 APEX: Successfully generated structural PDF via WebAssembly C++ Core for ${file.name}`);

        // Ensure branding is applied even to the native binary if requested
        if (options.addBranding) {
            const pdfDoc = await PDFDocument.load(wasmPdfBytes);
            pdfDoc.registerFontkit(fontkit);
            const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
            const pages = pdfDoc.getPages();
            const { width: pWidth } = pages[0].getSize();

            for (let i = 0; i < pages.length; i++) {
                const p = pages[i];
                p.drawText(`Generated by Apex Engine Professional Vector Core | Page ${i + 1} of ${pages.length}`, {
                    x: pWidth / 2 - 140,
                    y: 20,
                    size: 8,
                    font: font,
                    color: rgb(0.5, 0.5, 0.5)
                });
            }
            return await pdfDoc.save();
        }

        return wasmPdfBytes;
    }

    // 1. PHASE 31.3: Document Preservation Standard (DPS)
    // TRUE NATIVE XML IMPLEMENTATION (Used as fallback mapping if WASM C++ core is absent or still fetching)
    // We only have high-fidelity JS fallback for DOCX.
    if (!file.name.toLowerCase().endsWith('.docx')) {
        throw new Error("WASM Engine required for this file format. Fallback only available for .docx");
    }

    const zip = await JSZip.loadAsync(arrayBuffer);
    const docXmlFile = zip.file("word/document.xml");

    if (!docXmlFile) {
        throw new Error("Invalid or corrupted docx: missing word/document.xml core structural file.");
    }

    const xmlString = await docXmlFile.async("string");

    // --- Parse Relationships for Images ---
    const relsXmlFile = zip.file("word/_rels/document.xml.rels");
    const relsMap: Record<string, string> = {};
    if (relsXmlFile) {
        const relsString = await relsXmlFile.async("string");
        const relRegex = /<Relationship[^>]*Id="([^"]+)"[^>]*Target="([^"]+)"/g;
        let relMatch;
        while ((relMatch = relRegex.exec(relsString)) !== null) {
            relsMap[relMatch[1]] = relMatch[2];
        }
    }

    // Initialize standard Vector PDF with Custom Font Synthesis
    const pdfDoc = await PDFDocument.create();
    pdfDoc.registerFontkit(fontkit);

    // --- PHASE 31.3 A: TrueType & WOFF Emulation Mapping ---
    // Scan native OOXML architecture for any embedded font subsets
    let primaryEmulatedFont = null;
    let boldEmulatedFont = null;

    try {
        const fontFiles = Object.keys(zip.files).filter(name => name.match(/\.(ttf|otf|woff)$/i));
        for (const fontPath of fontFiles) {
            const fontBytes = await zip.file(fontPath)?.async("uint8array");
            if (fontBytes) {
                const synthesizedFont = await pdfDoc.embedFont(fontBytes);
                if (!primaryEmulatedFont) primaryEmulatedFont = synthesizedFont;
                else if (!boldEmulatedFont) boldEmulatedFont = synthesizedFont;
            }
        }
    } catch (e) {
        console.warn("WOFF Emulation failed, falling back to primitive Standard Fonts", e);
    }

    const font = primaryEmulatedFont || await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = boldEmulatedFont || await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    let page = pdfDoc.addPage([595.28, 841.89]); // A4 Size mathematically defined
    const { width, height } = page.getSize();

    let currentYPts = height - 50;
    const margin = 50;
    const lineHeight = 14;

    // Secure Regex parser for worker environments (No DOMParser needed)
    // Matches block-level elements: Paragraphs and Tables
    const blockRegex = /(<w:p[ >][\s\S]*?<\/w:p>|<w:tbl[ >][\s\S]*?<\/w:tbl>)/g;
    let blockMatch;

    while ((blockMatch = blockRegex.exec(xmlString)) !== null) {
        const pBlock = blockMatch[0];

        if (pBlock.startsWith('<w:p')) {
            // --- 1. HANDLE EMBEDDED IMAGES ---
            const drawingRegex = /<w:drawing[\s\S]*?<a:blip[^>]*r:embed="([^"]+)"/g;
            let drawingMatch;
            while ((drawingMatch = drawingRegex.exec(pBlock)) !== null) {
                const rId = drawingMatch[1];
                const target = relsMap[rId];
                if (target) {
                    const imgPath = target.startsWith('word/') ? target : `word/${target}`;
                    const imgFile = zip.file(imgPath);
                    if (imgFile) {
                        const imgData = await imgFile.async("uint8array");
                        let pdfImage = null;
                        try {
                            if (imgPath.toLowerCase().endsWith('.png')) {
                                pdfImage = await pdfDoc.embedPng(imgData);
                            } else if (imgPath.toLowerCase().match(/\.jpe?g$/)) {
                                pdfImage = await pdfDoc.embedJpg(imgData);
                            }
                        } catch (e) {
                            console.error("Failed to embed image", e);
                        }

                        if (pdfImage) {
                            const imgDims = pdfImage.scale(0.5); // Default scale
                            const drawWidth = Math.min(imgDims.width, width - margin * 2);
                            const drawHeight = imgDims.height * (drawWidth / imgDims.width);

                            if (currentYPts - drawHeight < margin) {
                                page = pdfDoc.addPage([595.28, 841.89]);
                                currentYPts = height - margin;
                            }

                            currentYPts -= drawHeight;
                            page.drawImage(pdfImage, {
                                x: margin,
                                y: currentYPts,
                                width: drawWidth,
                                height: drawHeight
                            });
                            currentYPts -= 20; // padding below image
                        }
                    }
                }
            }

            // --- 2. HANDLE TEXT ---
            const textRegex = /<w:t[^>]*>(.*?)<\/w:t>/g;
            let match;
            let pText = "";
            while ((match = textRegex.exec(pBlock)) !== null) {
                pText += match[1].replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'");
            }

            if (pText.trim() === "") {
                currentYPts -= lineHeight; // Spatial spacing for empty paragraphs
                continue;
            }

            const isBold = pBlock.includes('<w:b/>') || pBlock.includes('<w:b ');
            const _isItalic = pBlock.includes('<w:i/>') || pBlock.includes('<w:i ');

            const words = pText.split(' ');
            let currentLine = '';
            const currentFont = isBold ? boldFont : font;

            for (let n = 0; n < words.length; n++) {
                const testLine = currentLine + words[n] + ' ';
                const textWidth = currentFont.widthOfTextAtSize(testLine, 12);

                if (textWidth > width - margin * 2 && n > 0) {
                    if (currentYPts < margin) {
                        page = pdfDoc.addPage([595.28, 841.89]);
                        currentYPts = height - margin;
                    }
                    page.drawText(currentLine, { x: margin, y: currentYPts, size: 12, font: currentFont, color: rgb(0, 0, 0) });
                    currentLine = words[n] + ' ';
                    currentYPts -= lineHeight;
                } else {
                    currentLine = testLine;
                }
            }

            if (currentYPts < margin) {
                page = pdfDoc.addPage([595.28, 841.89]);
                currentYPts = height - margin;
            }
            page.drawText(currentLine, { x: margin, y: currentYPts, size: 12, font: currentFont, color: rgb(0, 0, 0) });
            currentYPts -= lineHeight * 1.5;

        } else if (pBlock.startsWith('<w:tbl')) {
            // --- 3. HANDLE TABLES ---
            const rowRegex = /<w:tr[ >][\s\S]*?<\/w:tr>/g;
            let rowMatch;
            currentYPts -= 10; // Padding before table

            while ((rowMatch = rowRegex.exec(pBlock)) !== null) {
                const rowStr = rowMatch[0];

                // Count cells to determine equal width
                let numCells = 0;
                const countRegex = /<w:tc[ >]/g;
                while (countRegex.exec(rowStr) !== null) numCells++;

                if (numCells === 0) continue;

                const actualColWidth = (width - margin * 2) / numCells;
                const rowHeight = 24;

                if (currentYPts - rowHeight < margin) {
                    page = pdfDoc.addPage([595.28, 841.89]);
                    currentYPts = height - margin;
                }

                const cellRegex = /<w:tc[ >][\s\S]*?<\/w:tc>/g;
                let cellMatch;
                let cellIndex = 0;
                const startY = currentYPts;

                while ((cellMatch = cellRegex.exec(rowStr)) !== null) {
                    const cellStr = cellMatch[0];
                    const textRegex = /<w:t[^>]*>(.*?)<\/w:t>/g;
                    let match;
                    let cText = "";
                    while ((match = textRegex.exec(cellStr)) !== null) {
                        cText += match[1].replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'");
                    }

                    const cellX = margin + (cellIndex * actualColWidth);
                    page.drawRectangle({
                        x: cellX,
                        y: startY - rowHeight,
                        width: actualColWidth,
                        height: rowHeight,
                        borderColor: rgb(0.7, 0.7, 0.7),
                        borderWidth: 1,
                    });

                    // Cap text to avoid overflowing cell visually (in a full engine we'd wrap)
                    let displayTxt = cText.trim();
                    if (font.widthOfTextAtSize(displayTxt, 10) > actualColWidth - 10) {
                        displayTxt = displayTxt.substring(0, Math.floor(actualColWidth / 6)) + "..";
                    }

                    if (displayTxt.length > 0) {
                        page.drawText(displayTxt, { x: cellX + 5, y: startY - 16, size: 10, font: font, color: rgb(0, 0, 0) });
                    }
                    cellIndex++;
                }
                currentYPts -= rowHeight;
            }
            currentYPts -= 10; // Padding after table
        }
    }

    // Native Branding Injection via Graphics State manipulation
    if (options.addBranding) {
        const pages = pdfDoc.getPages();
        for (let i = 0; i < pages.length; i++) {
            const p = pages[i];
            p.drawText(`Generated by PDFToolskit Professional Vector Engine | Page ${i + 1} of ${pages.length}`, {
                x: width / 2 - 120,
                y: 20,
                size: 8,
                font: font,
                color: rgb(0.6, 0.6, 0.6) // Precise #999999 shading
            });
        }
    }

    return await pdfDoc.save();
}
