import jsPDF from 'jspdf';
import mammoth from 'mammoth';

export interface WordToPdfOptions {
    addBranding?: boolean;
    onProgress?: (progress: number) => void;
}

export async function wordToPdf(file: File, options: WordToPdfOptions = {}): Promise<Uint8Array> {
    const arrayBuffer = await file.arrayBuffer();

    // 1. Convert DOCX to HTML using mammoth
    const result = await mammoth.convertToHtml({ arrayBuffer });
    const html = result.value;

    // 2. Wrap HTML in a professional container
    const container = document.createElement('div');
    container.style.width = '794px'; // A4 width at 96 DPI
    container.style.padding = '50px';
    container.style.backgroundColor = 'white';
    container.style.color = 'black';
    container.style.fontFamily = "'Inter', system-ui, sans-serif";
    container.style.lineHeight = '1.6';
    container.innerHTML = `
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap');
            table { width: 100%; border-collapse: collapse; margin-bottom: 24px; font-family: 'Inter', sans-serif; }
            th, td { border: 1px solid #e2e8f0; padding: 12px; text-align: left; }
            th { background-color: #f8fafc; font-weight: 700; }
            img { max-width: 100%; height: auto; display: block; margin: 20px 0; border-radius: 8px; }
            p { margin-bottom: 16px; font-size: 14px; }
            h1, h2, h3 { margin-top: 24px; margin-bottom: 16px; font-weight: 700; color: #1e293b; }
            h1 { font-size: 28px; }
            h2 { font-size: 22px; }
            h3 { font-size: 18px; }
        </style>
        ${html}
    `;

    document.body.appendChild(container);

    try {
        const doc = new jsPDF({
            orientation: 'p',
            unit: 'px',
            format: 'a4',
            hotfixes: ['px_scaling']
        });

        await new Promise<void>((resolve) => {
            doc.html(container, {
                callback: () => resolve(),
                x: 0,
                y: 0,
                autoPaging: 'text',
                width: 794,
                windowWidth: 794,
                margin: [40, 40, 40, 40]
            });
        });

        // Optional: Add Footer
        if (options.addBranding) {
            const totalPages = doc.getNumberOfPages();
            const pageWidth = doc.internal.pageSize.getWidth();
            const pageHeight = doc.internal.pageSize.getHeight();
            for (let i = 1; i <= totalPages; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setTextColor(160);
                doc.text(`Generated by PDFToolskit Professional | Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 15, { align: 'center' });
            }
        }

        return new Uint8Array(doc.output('arraybuffer'));
    } finally {
        document.body.removeChild(container);
    }
}
